### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by dpshee**
made the npm install global to solve issues when starting from scratch

### CODE REVIEW

**Comment by mattmazzola** [comment]
I don't think `-g` is appropriate here. It should only be installing dependencies for this local project. 
What issues were you having?

See: https://docs.npmjs.com/cli/install
> In global mode (ie, with -g or --global appended to the command), it installs the current package context (ie, the current working directory) as a global package.

**Comment by mattmazzola** [comment]
Well, I ran through these instructions on a Windows VM and it succeeded without errors.

I'm guessing there is some other environmental differences that are causing the error your seeing and we would need more information to understand.

Adding `-g` isn't the correct solution even though it happens to prevent issues for you.  I'm still not sure why or how that helps.  Normally usage of `-g` flag is to manually install packages specified inline such as: `npm install -g npm` which would update NPM.  If you're running `npm install -g` and it attempts to install all the dependencies of the current package as global packages instead of creating a local `node_modules` folder this seems like a bad practice.

We have build machines that use Windows VM's and they do run `npm install` and `npm run build` but they don't actually start the service so I can try to find a way to have them test that scenario as well, but we generally only run tasks that have finite lifetime with exit codes and `npm start` does not which makes it difficult.

I will leave PR open a few days for discussion if someone isolates the issue and close after since we won't this change.

**Comment by mattmazzola** [comment]
Can you check the `node_modules` folder and see that the `fetch_ponyfill` is actually missing?
I don't understand how the install can succeed while it didn't actually install a required package.

I was suspicious of trying this in the System32 folder instead of a normal user folder, but this shouldn't be issue.

Also, can you try updating NPM to see if that has any impact? It looks like you were on 5.6.0. Maybe try latest 5.x?

**Comment by dpshee** [comment]
The ```fetch_ponyfill``` module is missing. <br>
I ran ```npm install -g npm@latest``` to update npm from 5.6.0 to latest (6.0.1).  Doing this created the ```fetch_ponyfill``` module.  <br>
Running ```npm start``` with this env setup is now successful

**Comment by dpshee** [comment]
I did not explicitly re-run npm install
the fetch_ponyfill package is defiantly there now

**Comment by mattmazzola** [comment]
Ok.  I'm not sure how that happened, but glad you're unblocked and can play with the sample.

Most of these comments have been about a possible issue with NPM version requirements instead of about the PR so going to close.  We can continue discussion on #198 which seems to be the same error with `fetch_ponyfill`

**Pull request closed without merging**
